apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: net-sim
  {{- if .Values.ingress.funnel }}
  annotations:
    tailscale.com/funnel: "true"
  {{- end }}
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: net-sim
      port:
        number: {{ .Values.service.port }}
  tls:
    - hosts:
        - {{ .Values.ingress.hostname }}
